import { useEffect, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { loadState, saveState } from '../../src/storage';
import type { AppState, Payload } from '../../src/models';

export default function Settings(){const [state,setState]=useState<AppState|null>(null);const [profile,setProfile]=useState('Local operator');const [payloadName,setPayloadName]=useState('');const [payloadTags,setPayloadTags]=useState('');const [payloadDescription,setPayloadDescription]=useState('');useEffect(()=>{loadState().then(setState)},[]);if(!state)return <View style={styles.center}><Text style={styles.muted}>Loading…</Text></View>;
 async function addPayload(){if(!payloadName.trim())return;const p:Payload={id:`payload-${Date.now()}`,name:payloadName.trim(),description:payloadDescription.trim(),tags:payloadTags.split(',').map(x=>x.trim()).filter(Boolean)};const next={...state,payloads:[p,...state.payloads]};await saveState(next);setState(next);setPayloadName('');setPayloadTags('');setPayloadDescription('');}
 async function remove(id:string){const next={...state,payloads:state.payloads.filter(x=>x.id!==id)};await saveState(next);setState(next);}
 return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Text style={styles.kicker}>SETTINGS</Text><Text style={styles.title}>Workspace</Text><Text style={styles.section}>Local identity</Text><TextInput value={profile} onChangeText={setProfile} style={styles.input}/><View style={styles.notice}><Text style={styles.noticeTitle}>Authentication boundary</Text><Text style={styles.muted}>There is no server authentication yet. This profile is local UI state only and must not be treated as security.</Text></View><Text style={styles.section}>Payload catalogue</Text><TextInput value={payloadName} onChangeText={setPayloadName} placeholder="Name" placeholderTextColor="#71717a" style={styles.input}/><TextInput value={payloadTags} onChangeText={setPayloadTags} placeholder="Tags: office, demo" placeholderTextColor="#71717a" style={styles.input}/><TextInput value={payloadDescription} onChangeText={setPayloadDescription} placeholder="Description" placeholderTextColor="#71717a" style={[styles.input,{minHeight:80}]} multiline/><Pressable style={styles.primary} onPress={addPayload}><Text style={styles.primaryText}>Add catalogue entry</Text></Pressable>{state.payloads.map(p=><View key={p.id} style={styles.item}><View style={{flex:1}}><Text style={styles.itemTitle}>{p.name}</Text><Text style={styles.muted}>{p.description||'No description'} · {p.tags.join(', ')||'no tags'}</Text></View><Pressable onPress={()=>remove(p.id)}><Text style={styles.remove}>Delete</Text></Pressable></View>)}<Text style={styles.section}>Product capabilities</Text>{['Dashboard','Script editor','Create / delete','Remote execution','Payload catalogue','Execution history','Device management','Wi‑Fi UI','Remote API adapter'].map(x=><View key={x} style={styles.cap}><Text style={styles.check}>✓</Text><Text style={styles.capText}>{x}</Text></View>)}<Text style={styles.hint}>WebSocket telemetry, remote authentication, upload/delete endpoints and server-side device management remain backend work by design.</Text></ScrollView>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#09090b'},content:{padding:20,gap:9},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#09090b'},kicker:{color:'#a78bfa',fontSize:11,fontWeight:'800',letterSpacing:2},title:{color:'#fff',fontSize:32,fontWeight:'800'},section:{color:'#fff',fontSize:19,fontWeight:'700',marginTop:16},input:{backgroundColor:'#18181b',borderColor:'#27272a',borderWidth:1,borderRadius:12,padding:13,color:'#fff'},primary:{padding:15,backgroundColor:'#7c3aed',borderRadius:12,alignItems:'center'},primaryText:{color:'#fff',fontWeight:'800'},notice:{backgroundColor:'#111113',borderWidth:1,borderColor:'#27272a',borderRadius:14,padding:14},noticeTitle:{color:'#fff',fontWeight:'700',marginBottom:4},muted:{color:'#a1a1aa',lineHeight:20},item:{flexDirection:'row',alignItems:'center',gap:10,padding:14,backgroundColor:'#18181b',borderColor:'#27272a',borderWidth:1,borderRadius:14},itemTitle:{color:'#fff',fontWeight:'700'},remove:{color:'#f87171',fontWeight:'700'},cap:{flexDirection:'row',gap:10,alignItems:'center',paddingVertical:7},check:{color:'#4ade80',fontWeight:'900'},capText:{color:'#d4d4d8'},hint:{color:'#71717a',lineHeight:19,marginTop:10}});
